### ISSUE TITLE
LSP crashes when adding or removing lines within code fences

### ISSUE THREAD

**Issue by tjex** [zk-org/zk#461]
### Check if applicable

- [x] I have searched the existing issues (**required**)
- [x] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

While editing within code fences, I'm finding that adding lines (i.e, with `<cr>` or `[o|O]`) or removing them (`<BS>` or `dd`) that the LSP crashes with "exit code 2 and signal 0".

Here are the lsp logs:

```text
[START][2024-10-05 18:46:43] LSP logging initiated
[ERROR][2024-10-05 18:46:43] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/tjex/.local/share/nvim/mason/bin/marksman"	"stderr"	"[18:46:43 INF] <LSP Entry> Starting Marksman LSP server: {}\n"
[ERROR][2024-10-05 18:46:52] .../vim/lsp/rpc.lua:770	"rpc"	"zk"	"stderr"	"panic: runtime error: slice bounds out of range [:3] with length 0\n\ngoroutine 25 [running"
[ERROR][2024-10-05 18:46:52] .../vim/lsp/rpc.lua:770	"rpc"	"zk"	"stderr"	"]:\ngithub.com/zk-org/zk/internal/adapter/lsp.isLineWithinCodeBlock({0x1400048c000, 0x17, 0x100cf3000?}, 0x1?, {0x140003ec677, 0x6})\n\t/Users/tjex/.local/src/zk-org/zk/main/internal/adapter/lsp/document.go:222 +0x2c8\ngithub.com/zk-org/zk/internal/adapter/lsp.(*document).DocumentLinks(0x140000423c0)\n\t/Users/tjex/.local/src/zk-org/zk/main/internal/adapter/lsp/document.go:262 +0x10c\ngithub.com/zk-org/zk/internal/adapter/lsp.(*Server).refreshDiagnosticsOfDocument.func1()\n\t/Users/tjex/.local/src/zk-org/zk/main/internal/adapter/lsp/server.go:596 +0x70\ncreated by github.com/zk-org/zk/internal/adapter/lsp.(*Server).refreshDiagnosticsOfDocument in goroutine 23\n\t/Users/tjex/.local/src/zk-org/zk/main/internal/adapter/lsp/server.go:589 +0x10c\n"
```

We worked on code handling links within code fences here, https://github.com/zk-org/zk/pull/399. Perhaps this change introduced a bug.

### How to reproduce?

1. Create a new note.
2. Add code fences with or without lang definition.
3. Add a line or two within the code fences, delete, add, etc.

At some point the LSP should crash.

If text is added directly at the last line _first_, and code fences are added then somewhere above it, then the bug _doesn't_ occur. 

If the file is _saved_ with text occupying the last line, and then reopened, and a code block is added somewhere _above_ the last line, then the bug _does_ occur.

### zk configuration

na

### Environment

zk 0.14.1-23-gbe5bd76
system: Darwin 23.6.0 arm64

**Comment by dandeandean** [comment]
Hey @tjex I've been able to reproduce this locally. If you're not actively developing on this, I could pick up this bug.

**Comment by tjex** [comment]
@dandeandean I haven't managed to get around to this. It would be incredibly appreciated if you did!

**Comment by dandeandean** [comment]
@tjex Sounds good, I am looking into it now.
